development:
  adapter: async

test:
  adapter: async

production:
  production:
  adapter: postgresql
  url: postgres://redhhtocgomhdc:7e8128a7503754f97cefe2f2d2d01353ac96876e54fc33ce6d96ff8069b92a20@ec2-107-22-221-60.compute-1.amazonaws.com:5432/dbq2n5p408ksg5
